server:
  port: 9099
  context-path: /jwt-demo

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jwt-demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111111

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

jwt:
  header: Authorization
  secret: TfjsGltjlsdfjWJ9FSL
  expiration: 604800
